// SPDX-License-Identifier: MIT
// Copyright © 2026 AtomGradient
// 版权所有 © 2026 质子梯度（北京）科技有限公司
// Generated by scripts/generate_harness_swift_contract.py. Do not hand-edit.

import Foundation

enum HarnessContract {
    static let version = 1
    static let maxMessageBytes = 1_048_576
    static let operationRegistryDigest = "e23f51798c6ae31f9f3c0cc593e18284aa49c63ce1b3efd98fee4656ec1f3c03"

    static let capabilities: [String: String] = [
        "host.status": "host.read",
        "presentation.permission-probe": "participant.read",
        "presentation.permission-request": "participant.manage",
        "environment.probe": "participant.read",
        "project.register": "project.manage",
        "project.list": "project.read",
        "project.reconcile": "project.manage",
        "project.accept-reconciliation": "project.manage",
        "project.unregister": "project.manage",
        "project.bootstrap": "project.manage",
        "scenario.create": "scenario.manage",
        "scenario.list": "scenario.read",
        "scenario.open": "scenario.manage",
        "scenario.close": "scenario.manage",
        "scenario.start-participants": "participant.manage",
        "scenario.status": "scenario.read",
        "scenario.diagnostic": "scenario.read",
        "scenario.preflight": "scenario.read",
        "scenario.topology": "scenario.read",
        "scenario.focus": "scenario.manage",
        "scenario.repair": "scenario.repair",
        "scenario.destroy.preview": "scenario.read",
        "scenario.destroy": "scenario.destroy",
        "scenario.force-destroy": "scenario.destroy",
        "workspace.plan": "workspace.manage",
        "workspace.provision": "workspace.manage",
        "participant.list": "participant.read",
        "participant.template.list": "participant.read",
        "participant.add": "participant.manage",
        "participant.start": "participant.manage",
        "participant.stop": "participant.manage",
        "participant.recover": "participant.manage",
        "participant.replace": "participant.manage",
        "participant.force-stop": "participant.force-stop",
        "participant.destroy": "participant.manage",
        "resource.list": "resource.read",
        "resource.break": "resource.break",
        "policy.template.list": "policy.read",
        "policy.plan": "policy.read",
        "policy.apply-plan": "policy.manage",
        "policy.show": "policy.read",
        "delivery.list": "delivery.read",
        "delivery.retry": "delivery.send",
    ]

    static let confirmationPolicies: [String: String] = [
        "scenario.repair": "confirmation.destructive-once",
        "scenario.destroy": "confirmation.destructive-once",
        "scenario.force-destroy": "confirmation.destructive-once",
        "participant.force-stop": "confirmation.destructive-once",
        "resource.break": "confirmation.destructive-once",
    ]
}
