#!/usr/bin/env python3
# Copyright © 2026 AtomGradient
# 版权所有 © 2026 质子梯度（北京）科技有限公司

"""Generate or verify the macOS App binding to the typed Host registry."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ai_collab.protocol import (
    CONTRACT_VERSION,
    MAX_MESSAGE_BYTES,
    OPERATION_BY_ID,
    OPERATION_REGISTRY_DIGEST,
)


APP_OPERATIONS = (
    "host.status",
    "project.register",
    "project.list",
    "scenario.create",
    "scenario.list",
    "scenario.open",
    "scenario.close",
    "scenario.status",
    "scenario.diagnostic",
    "scenario.preflight",
    "scenario.topology",
    "scenario.focus",
    "scenario.repair",
    "scenario.destroy.preview",
    "scenario.destroy",
    "scenario.force-destroy",
    "workspace.plan",
    "workspace.provision",
    "participant.list",
    "participant.template.list",
    "participant.add",
    "participant.start",
    "participant.stop",
    "participant.recover",
    "participant.replace",
    "participant.detach",
    "participant.force-stop",
    "resource.list",
    "resource.break",
    "policy.template.list",
    "policy.plan",
    "policy.apply-plan",
    "policy.show",
    "delivery.list",
    "delivery.retry",
)
OUTPUT = (
    ROOT
    / "macos/AI-Collab/App/HarnessContract.generated.swift"
)


def render() -> str:
    rows = "\n".join(
        f'        "{operation}": "{OPERATION_BY_ID[operation]["required_capability"]}",'
        for operation in APP_OPERATIONS
    )
    confirmation_rows = "\n".join(
        f'        "{operation}": "{OPERATION_BY_ID[operation]["confirmation_policy_ref"]}",'
        for operation in APP_OPERATIONS
        if OPERATION_BY_ID[operation]["confirmation_policy_ref"] is not None
    )
    return f'''// Generated by scripts/generate_harness_swift_contract.py. Do not hand-edit.

import Foundation

enum HarnessContract {{
    static let version = {CONTRACT_VERSION}
    static let maxMessageBytes = {MAX_MESSAGE_BYTES:_}
    static let operationRegistryDigest = "{OPERATION_REGISTRY_DIGEST}"

    static let capabilities: [String: String] = [
{rows}
    ]

    static let confirmationPolicies: [String: String] = [
{confirmation_rows}
    ]
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    expected = render()
    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("Swift Harness contract binding is stale")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
